### ISSUE TITLE
EnsureMessagingEntityExists creates entity unconditionally

### ISSUE THREAD

**Issue by lencharest** [drub0y/Obvs.AzureServiceBus#1]
In file `Obvs.AzureServiceBus/Obvs.AzureServiceBus/Configuration/MessageClientEntityFactory.cs`, the method `MessageClientEntityFactory.EnsureMessagingEntityExists` calls local function `create()` regardless of whether the target messaging entity already exists. If the entity does already exist, Azure Service Bus throws a `MessagingEntityAlreadyExistsException`.

The simplest (but not necessarily best) fix is to wrap `if (!alreadyExists) { ... }` around the try/catch block starting at line 244.

**Comment by drub0y** [comment]
Ah, yeah I see. I was focused on testing the temp stuff, clearly need tests to cover this scenario as well. Will try to patch up on flight home from // BUILD.

**Comment by lencharest** [comment]
The fix can wait. I've already patched and rebuilt the code on my dev box.
Relax on your flight.

**Comment by drub0y** [comment]
Fixed by 355b5780.
